### ISSUE TITLE
No way to turn of the discover option

### ISSUE THREAD

**Issue by dpoltoratsky** [haroldadmin/functions-differ#12]
Despite what documentation says, the current default state of the discover option is `true`: https://github.com/haroldadmin/functions-differ/blob/main/src/options/options.ts#L12

And there is no way to turn it off.

Please either set the default to `false` or implement the negating flag: https://github.com/75lb/command-line-args/wiki/How-to-implement-a-negating-flag

**Comment by haroldadmin** [comment]
Thanks for raising this issue. A fix should be available in the next release.

**Comment by haroldadmin** [comment]
PR #13 adds a `--no-discover` flag to fix this issue. It's available in the [0.3.1](https://github.com/haroldadmin/functions-differ/releases/tag/0.3.1) release.
Feel free to reopen this issue if you feel the fix doesn't address your problem completely.

**Comment by dpoltoratsky** [comment]
Thanks for such a quick turnaround!
