### ISSUE TITLE
Support for custom esbuild config files 

### ISSUE THREAD

**Issue by hiiambhanu** [haroldadmin/functions-differ#7]
# Problem
The esbuild bundler may fail for some projects, such as one using `NestJs` because it may try to bundle the external dependencies as well, or due to some other reasons, which can be easily fixed by tweaking the `BuildOptions` of the bundler.

# Proposed Solution
Support for custom `esbuild config file` can be added to fix this issue easily. A `.json` file containing the various tweakable options can be passed onto the CLI which can then be parsed and passed onto the bundler.

**Comment by haroldadmin** [comment]
Closed with #8
